
print ('what is your name? ')
name = input()
print ('nice to meet you ' + name + '\n')
print ('the length of your name is ')
print (len(name))
print ('how old are you? ')
age = input()
print ('you will be ' + str(int(age)+4) + ' next four years' '\n')
print('what is your complexion? ')
complexion = input()
print('what is your height? ')
height = input()
print ('what will you like to become in future? ')
occupation = input()
print ('where are you from? ')
address = input ()
print ('what is the name of your best friend')
friend = input()
print ('composition' + '\n')
print ('my name is '+ name + ' \ni am ' + age + ' years old\ni am ' + complexion + ' in complexion')
print ('i am ' + height + ' in height' '\ni will like to become a ' + occupation + ' \ni am from ' + address + ' L.G.A.')

